// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// DO NOT USE RELATIVE IMPORTS EVEN IF THEY ARE AUTO-GENERATED!!

import { application } from "controllers/application"

import RailController from "controllers/rail_controller"
application.register("rail", RailController)
